name: Auto Test MS Graph API

on: 
  release:
    types: [published]
  push:
    branches: 
      - main
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:
   
jobs:
   Task:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python #安装python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id 提供
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # secrets_key 提供
      run: | 
        cp test.py 2.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '10 r configid.txt' 2.py
        sed -i '12 r configkey.txt' 2.py
    - name: Test Api #Api调用
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python 2.py
    - name: Delete secrets config #删除机密
      run: | 
        rm -f 2.py
        rm -f configid.txt
        rm -f configkey.txt    
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --global user.email chrisvcg_msdev@outlook.com
        git config --global user.name chrisvcg_msdev
        git add .
        git commit -m "update new refresh token with GitAction" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
